version: 1.0.0
collector_home: ./runtime
collector_version: 0.118.0
refinery_home: ./runtime
refinery_version: 2.9.2
otel_collector:
  bin_path: ./runtime/otelcol-contrib
  config_path: ./runtime/otelcol-config.yml
  send_auto: false
  send_endpoint: https://api.honeycomb.io
  send_apikey: ''
refinery:
  bin_path: ./runtime/refinery
  config_path: ./runtime/refinery-config.yml
  rule_path: ./runtime/refinery-rule.yml
  send_auto: false
  send_endpoint: https://api.honeycomb.io
  send_apikey: ''
work_dir: ./
template_dir: ./templates
collector_installed: true
refinery_installed: true
collector_config_exists: true
refinery_config_exists: true
refinery_rule_exists: true
os.arch: arm64
os.is64bit: true
os.platform: darwin
