services:
  oteltester:
    environment:
      OPENAI_API_KEY: ""
      OPENAI_MODEL: "gpt-4o"
    build:
      context: .
      dockerfile: Dockerfile
    image: oteltester:latest
    ports:
      - "3000:3000"
      - "3001:3001"